#!/bin/sh
#
### BEGIN INIT INFO
# Provides:          peba
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start PEBA
# Description:       Start Python EWS Backend.
### END INIT INFO

if [ `id -u` -ne 0 ]; then
        echo "You need root privileges to run this script"
        exit 1
fi

APPNAME=peba
USER=root
PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin
APPPATH=/opt/peba/
ACTIVATE=/opt/peba/bin/activate
APPMODULE=peba:app
DAEMON=/opt/peba/bin/gunicorn
PIDFILE=/var/run/gunicorn.pid
LOGFILE=/var/log/$APPNAME.log
WORKERS=4
BINDHOST=$(cat /etc/ews/peba.cfg|grep BINDHOST|cut -d "\"" -f2)


. /lib/lsb/init-functions



case "$1" in
  start)
        log_daemon_msg "Starting deferred execution scheduler" "$APPNAME"
        cd $APPPATH
        source $ACTIVATE
        cd $APPPATH
        $DAEMON --daemon --bind=$BINDHOST --pid=$PIDFILE --workers=$WORKERS --user=$USER --log-file=$LOGFILE $APPMODULE
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping deferred execution scheduler" "$APPNAME"
        killproc -p $PIDFILE $DAEMON
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$APPNAME {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0