#!/bin/bash

# let this script run once every 24h to create new daily indices.
# 0 0 * * * /pathToScript/rollindex_cron.sh

curl -XPOST {{ ELASTIC_IP }}:{{ ELASTIC_PORT }}/{{ ELASTIC_INDEX }}'/_rollover?pretty' -H 'Content-Type: application/json' -d'
{
   "conditions":{
      "max_age":"720m"
   },
   "settings":{
      "number_of_shards":5,
      "number_of_replicas":1
   },
   "mappings":{
      "Alert":{
         "properties":{
            "additionalData":{
               "type":"keyword",
               "index":"false"
            },
            "client":{
               "type":"keyword",
               "index":"false"
            },
            "clientDomain":{
               "type":"bool",
               "index":"true"
            },
            "clientVersion":{
               "type":"keyword",
               "index":"false"
            },
            "country":{
               "type":"keyword",
               "index":"false"
            },
            "countryName":{
               "type":"keyword",
               "index":"true"
            },
            "createTime":{
               "type":"date",
               "format":"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis"
            },
            "externalIP":{
               "type":"ip",
               "index":"false"
            },
            "hostname":{
               "type":"keyword",
               "index":"true"
            },
            "internalIP":{
               "type":"ip",
               "index":"false"
            },
            "location":{
               "type":"keyword",
               "index":"false"
            },
            "locationDestination":{
               "type":"keyword",
               "index":"false"
            },
            "login":{
               "type":"keyword",
               "index":"false"
            },
            "originalRequestString":{
               "type":"keyword",
               "index":"true"
            },
            "password":{
               "type":"keyword",
               "index":"false"
            },
            "peerIdent":{
               "type":"keyword",
               "index":"true"
            },
            "peerType":{
               "type":"keyword",
               "index":"true"
            },
            "rawhttp":{
               "type":"keyword",
               "index":"false"
            },
            "recievedTime":{
               "type":"date",
               "format":"yyyy-MM-dd HH:mm:ss||yyyy-MM-dd||epoch_millis",
               "index":"yes"
            },
            "sessionEnd":{
               "type":"keyword",
               "index":"false"
            },
            "sessionStart":{
               "type":"keyword",
               "index":"false"
            },
            "sourceEntryAS":{
               "type":"keyword",
               "index":"true"
            },
            "sourceEntryIp":{
               "type":"ip",
               "index":"true"
            },
            "sourceEntryPort":{
               "type":"keyword",
               "index":"false"
            },
            "targetCountry":{
               "type":"keyword",
               "index":"no"
            },
            "targetCountryName":{
               "type":"keyword",
               "index":"true"
            },
            "targetEntryAS":{
               "type":"keyword",
               "index":"false"
            },
            "targetEntryIp":{
               "type":"ip",
               "index":"true"
            },
            "targetEntryPort":{
               "type":"keyword",
               "index":"false"
            },
            "targetport":{
               "type":"keyword",
               "index":"false"
            },
            "username":{
               "type":"keyword",
               "index":"false"
            },
            "vulnid":{
               "type":"keyword",
               "index":"false"
            }
         }
      }
   }
}
'
